apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    app: mysql-slave
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: mysql
  clusterIP: None
  selector:
    app: mysql-slave
