apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
  labels:
    app: todoapi
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: todoapi
    spec:
      serviceAccountName: {{ include "todoapp.serviceAccountName" . }}
      containers:
        - name: nginx
          image: gihyodocker/nginx:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: WORKER_PROCESSES
              value: "2"
            - name: WORKER_CONNECTIONS
              value: "1024"
            - name: LOG_STDOUT
              value: "true"
            - name: BACKEND_HOST
              value: "localhost:8080"
        - name: api
          image: gihyodocker/todoapi:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 8080       
          env:
          - name: TODO_BIND
            value: ":8080"
          - name: TODO_MASTER_URL
            value: "gihyo:gihyo@tcp(mysql-master:3306)/tododb?parseTime=true"
          - name: TODO_SLAVE_URL
            value: "gihyo:gihyo@tcp(mysql-slave:3306)/tododb?parseTime=true"

